#!/bin/sh

# HOT TO SETUP
# mkdir -p /opt/GuestSDK/bin/bin64
# cp -p vmware-appmonitor /opt/GuestSDK/bin/bin64
# chmod +x /opt/GuestSDK/bin/bin64/vmware-appmonitor

case ${1} in
enable)
        exit 0
        ;;
disable)
        exit 0
        ;;
isEnabled)
        exit 1
        #exit 0
        ;;
markActive)
	echo "### markActive ###" >&2 
        exit 0
        ;;
*)
        exit 1
        ;;
esac
